<footer class="bg-purple-100">
	<div class="container">
		<div class="footer-column">
			<h3>Etech.</h3>
			<p>Immerse yourself in a world of technologies</p>
			<div class="social-icons">
				<a href="#"><i class="fab fa-facebook"></i></a>
				<a href="#"><i class="fa-brands fa-instagram"></i></a>
				<a href="#"><i class="fa-brands fa-x-twitter"></i></a>
			</div>
		</div>
		<div class="footer-column">
			<h3>Company</h3>
			<a href="about.php">About Us</a>
			<a href="jobs.php">Apply Now</a>
		</div>
		<div class="footer-column">
			<h3>Contact Us</h3>
			<p>+1 (234) 123-4567</p>
			<p>etechinfo@gmail.com</p>
		</div>
	</div>
	<div class="footer-bottom">
		Copyright &copy; 2023 Etech. All rights reserved
	</div>
</footer>
</body>
</html>