<header class="bg-white">
	<div class="container">
		<!-- Container box -->
		<div class="logo">
			Etech.
		</div>
    	<input type="checkbox" id="menu-toggle">
		<label for="menu-toggle" class="menu-icon">
		&#9776;
		</label>
		<nav>
			<a href="index.php">
			Home
			</a>
			<a href="about.php">
			About Us
			</a>
			<a href="jobs.php">
			Jobs
			</a>
			<a href="apply.php">
			Apply
			</a>
			<a href="enhancements.php">
			Enhancements
			</a>
		</nav>
	</div>
</header>